/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AddBranchRequest, AddBranchValue, AdoptTranslationRequest, AdoptTranslationValue, AnalyseParagraphRequest, AnalyseParagraphResult, AnalyseSentenceRequest, AnalyseSentenceResult, AnalysisCoverageValue, ArchivePassageRequest, ArchivePassageValue, AskFrame, AskRequest, AskResult, CancelAnalysisRequest, CancelAnalysisValue, ConjugationRequest, CreateBranchRequest, CreateBranchValue, CreateLexiconEntryRequest, CreateLexiconEntryValue, CreatePassageRequest, CreatePassageValue, CreateSelectionRequest, CreateSelectionValue, DiscussionView, ExportLibraryRequest, ExportLibraryValue, ExportPassagesValue, FetchConjugationValue, FetchLexiconSourceRequest, FetchLexiconSourceValue, GetPassageRequest, GetPassageValue, GetSegmentationRequest, GetSegmentationValue, ImportLibraryRequest, ImportLibraryValue, ImportPreviewValue, LexiconLookup, ListAnalysisRequest, ListAnalysisValue, ListBackendModelsRequest, ListBackendModelsValue, ListBackendsRequest, ListBackendsValue, ListDiscussionRequest, ListGrammarRequest, ListGrammarValue, ListLexiconRequest, ListLexiconSourcesRequest, ListLexiconSourcesValue, ListLexiconValue, ListPassagesRequest, ListPassagesValue, LookupMotRequest, PreviewAnalysisContextRequest, PreviewAnalysisContextValue, PreviewAskRequest, PreviewAskValue, PreviewImportRequest, PublishAnalysisRequest, PublishAnalysisValue, PutSentenceAnalysisRequest, PutSentenceAnalysisValue, ReadAnalysisCoverageRequest, ReadConjugationValue, ReadContextRequest, ReadContextValue, ReadSentenceAnalysisRequest, ReadSentenceAnalysisValue, RecordConclusionRequest, RecordConclusionValue, RenderLexiconRequest, RenderLexiconValue, ResolveGrammarRequest, ResolveGrammarValue, RestorePassageRequest, RestorePassageValue, SaveTranslationRequest, SaveTranslationValue, SetBranchStateRequest, SetBranchStateValue, SetGrammarMasteryRequest, SetGrammarMasteryValue } from '@local/french-close-reading/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6672656e6368526561646572 {
    addBranch: (request: AddBranchRequest, signal?: AbortSignal) => Promise<RemoteResult<AddBranchValue>>
    adoptTranslation: (request: AdoptTranslationRequest, signal?: AbortSignal) => Promise<RemoteResult<AdoptTranslationValue>>
    analyseParagraph: (request: AnalyseParagraphRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalyseParagraphResult>>
    analyseSentence: (request: AnalyseSentenceRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalyseSentenceResult>>
    archivePassage: (request: ArchivePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<ArchivePassageValue>>
    ask: (request: AskRequest, signal?: AbortSignal) => Promise<RemoteResult<AskResult>>
    cancelAnalysis: (request: CancelAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<CancelAnalysisValue>>
    createBranch: (request: CreateBranchRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateBranchValue>>
    createLexiconEntry: (request: CreateLexiconEntryRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateLexiconEntryValue>>
    createPassage: (request: CreatePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<CreatePassageValue>>
    createSelection: (request: CreateSelectionRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateSelectionValue>>
    exportLibrary: (request: ExportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportLibraryValue>>
    exportPassages: (signal?: AbortSignal) => Promise<RemoteResult<ExportPassagesValue>>
    fetchConjugation: (request: ConjugationRequest, signal?: AbortSignal) => Promise<RemoteResult<FetchConjugationValue>>
    fetchLexiconSource: (request: FetchLexiconSourceRequest, signal?: AbortSignal) => Promise<RemoteResult<FetchLexiconSourceValue>>
    getPassage: (request: GetPassageRequest, signal?: AbortSignal) => Promise<RemoteResult<GetPassageValue>>
    getSegmentation: (request: GetSegmentationRequest, signal?: AbortSignal) => Promise<RemoteResult<GetSegmentationValue>>
    importLibrary: (request: ImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportLibraryValue>>
    listAnalysis: (request: ListAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<ListAnalysisValue>>
    listArchivedPassages: (request: ListPassagesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListPassagesValue>>
    listBackendModels: (request: ListBackendModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<ListBackendModelsValue>>
    listBackends: (request: ListBackendsRequest, signal?: AbortSignal) => Promise<RemoteResult<ListBackendsValue>>
    listDiscussion: (request: ListDiscussionRequest, signal?: AbortSignal) => Promise<RemoteResult<DiscussionView>>
    listGrammar: (request: ListGrammarRequest, signal?: AbortSignal) => Promise<RemoteResult<ListGrammarValue>>
    listLexicon: (request: ListLexiconRequest, signal?: AbortSignal) => Promise<RemoteResult<ListLexiconValue>>
    listLexiconSources: (request: ListLexiconSourcesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListLexiconSourcesValue>>
    listPassages: (request: ListPassagesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListPassagesValue>>
    lookupMot: (request: LookupMotRequest, signal?: AbortSignal) => Promise<RemoteResult<LexiconLookup>>
    previewAnalysisContext: (request: PreviewAnalysisContextRequest, signal?: AbortSignal) => Promise<RemoteResult<PreviewAnalysisContextValue>>
    previewAsk: (request: PreviewAskRequest, signal?: AbortSignal) => Promise<RemoteResult<PreviewAskValue>>
    previewImport: (request: PreviewImportRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportPreviewValue>>
    publishAnalysis: (request: PublishAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<PublishAnalysisValue>>
    putSentenceAnalysis: (request: PutSentenceAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<PutSentenceAnalysisValue>>
    readAnalysisCoverage: (request: ReadAnalysisCoverageRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalysisCoverageValue>>
    readConjugation: (request: ConjugationRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadConjugationValue>>
    readContext: (request: ReadContextRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadContextValue>>
    readSentenceAnalysis: (request: ReadSentenceAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadSentenceAnalysisValue>>
    recordConclusion: (request: RecordConclusionRequest, signal?: AbortSignal) => Promise<RemoteResult<RecordConclusionValue>>
    renderLexicon: (request: RenderLexiconRequest, signal?: AbortSignal) => Promise<RemoteResult<RenderLexiconValue>>
    resolveGrammarCandidate: (request: ResolveGrammarRequest, signal?: AbortSignal) => Promise<RemoteResult<ResolveGrammarValue>>
    restorePassage: (request: RestorePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<RestorePassageValue>>
    saveTranslation: (request: SaveTranslationRequest, signal?: AbortSignal) => Promise<RemoteResult<SaveTranslationValue>>
    setBranchState: (request: SetBranchStateRequest, signal?: AbortSignal) => Promise<RemoteResult<SetBranchStateValue>>
    setGrammarMastery: (request: SetGrammarMasteryRequest, signal?: AbortSignal) => Promise<RemoteResult<SetGrammarMasteryValue>>
    streamAsk: (request: AskRequest, signal?: AbortSignal) => RemoteStreamHandle<AskFrame, never>
  }
  interface TypertRemoteMap {
    'frenchReader/addBranch': (request: AddBranchRequest, signal?: AbortSignal) => Promise<RemoteResult<AddBranchValue>>
    'frenchReader/adoptTranslation': (request: AdoptTranslationRequest, signal?: AbortSignal) => Promise<RemoteResult<AdoptTranslationValue>>
    'frenchReader/analyseParagraph': (request: AnalyseParagraphRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalyseParagraphResult>>
    'frenchReader/analyseSentence': (request: AnalyseSentenceRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalyseSentenceResult>>
    'frenchReader/archivePassage': (request: ArchivePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<ArchivePassageValue>>
    'frenchReader/ask': (request: AskRequest, signal?: AbortSignal) => Promise<RemoteResult<AskResult>>
    'frenchReader/cancelAnalysis': (request: CancelAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<CancelAnalysisValue>>
    'frenchReader/createBranch': (request: CreateBranchRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateBranchValue>>
    'frenchReader/createLexiconEntry': (request: CreateLexiconEntryRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateLexiconEntryValue>>
    'frenchReader/createPassage': (request: CreatePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<CreatePassageValue>>
    'frenchReader/createSelection': (request: CreateSelectionRequest, signal?: AbortSignal) => Promise<RemoteResult<CreateSelectionValue>>
    'frenchReader/exportLibrary': (request: ExportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportLibraryValue>>
    'frenchReader/exportPassages': (signal?: AbortSignal) => Promise<RemoteResult<ExportPassagesValue>>
    'frenchReader/fetchConjugation': (request: ConjugationRequest, signal?: AbortSignal) => Promise<RemoteResult<FetchConjugationValue>>
    'frenchReader/fetchLexiconSource': (request: FetchLexiconSourceRequest, signal?: AbortSignal) => Promise<RemoteResult<FetchLexiconSourceValue>>
    'frenchReader/getPassage': (request: GetPassageRequest, signal?: AbortSignal) => Promise<RemoteResult<GetPassageValue>>
    'frenchReader/getSegmentation': (request: GetSegmentationRequest, signal?: AbortSignal) => Promise<RemoteResult<GetSegmentationValue>>
    'frenchReader/importLibrary': (request: ImportLibraryRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportLibraryValue>>
    'frenchReader/listAnalysis': (request: ListAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<ListAnalysisValue>>
    'frenchReader/listArchivedPassages': (request: ListPassagesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListPassagesValue>>
    'frenchReader/listBackendModels': (request: ListBackendModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<ListBackendModelsValue>>
    'frenchReader/listBackends': (request: ListBackendsRequest, signal?: AbortSignal) => Promise<RemoteResult<ListBackendsValue>>
    'frenchReader/listDiscussion': (request: ListDiscussionRequest, signal?: AbortSignal) => Promise<RemoteResult<DiscussionView>>
    'frenchReader/listGrammar': (request: ListGrammarRequest, signal?: AbortSignal) => Promise<RemoteResult<ListGrammarValue>>
    'frenchReader/listLexicon': (request: ListLexiconRequest, signal?: AbortSignal) => Promise<RemoteResult<ListLexiconValue>>
    'frenchReader/listLexiconSources': (request: ListLexiconSourcesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListLexiconSourcesValue>>
    'frenchReader/listPassages': (request: ListPassagesRequest, signal?: AbortSignal) => Promise<RemoteResult<ListPassagesValue>>
    'frenchReader/lookupMot': (request: LookupMotRequest, signal?: AbortSignal) => Promise<RemoteResult<LexiconLookup>>
    'frenchReader/previewAnalysisContext': (request: PreviewAnalysisContextRequest, signal?: AbortSignal) => Promise<RemoteResult<PreviewAnalysisContextValue>>
    'frenchReader/previewAsk': (request: PreviewAskRequest, signal?: AbortSignal) => Promise<RemoteResult<PreviewAskValue>>
    'frenchReader/previewImport': (request: PreviewImportRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportPreviewValue>>
    'frenchReader/publishAnalysis': (request: PublishAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<PublishAnalysisValue>>
    'frenchReader/putSentenceAnalysis': (request: PutSentenceAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<PutSentenceAnalysisValue>>
    'frenchReader/readAnalysisCoverage': (request: ReadAnalysisCoverageRequest, signal?: AbortSignal) => Promise<RemoteResult<AnalysisCoverageValue>>
    'frenchReader/readConjugation': (request: ConjugationRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadConjugationValue>>
    'frenchReader/readContext': (request: ReadContextRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadContextValue>>
    'frenchReader/readSentenceAnalysis': (request: ReadSentenceAnalysisRequest, signal?: AbortSignal) => Promise<RemoteResult<ReadSentenceAnalysisValue>>
    'frenchReader/recordConclusion': (request: RecordConclusionRequest, signal?: AbortSignal) => Promise<RemoteResult<RecordConclusionValue>>
    'frenchReader/renderLexicon': (request: RenderLexiconRequest, signal?: AbortSignal) => Promise<RemoteResult<RenderLexiconValue>>
    'frenchReader/resolveGrammarCandidate': (request: ResolveGrammarRequest, signal?: AbortSignal) => Promise<RemoteResult<ResolveGrammarValue>>
    'frenchReader/restorePassage': (request: RestorePassageRequest, signal?: AbortSignal) => Promise<RemoteResult<RestorePassageValue>>
    'frenchReader/saveTranslation': (request: SaveTranslationRequest, signal?: AbortSignal) => Promise<RemoteResult<SaveTranslationValue>>
    'frenchReader/setBranchState': (request: SetBranchStateRequest, signal?: AbortSignal) => Promise<RemoteResult<SetBranchStateValue>>
    'frenchReader/setGrammarMastery': (request: SetGrammarMasteryRequest, signal?: AbortSignal) => Promise<RemoteResult<SetGrammarMasteryValue>>
    'frenchReader/streamAsk': (request: AskRequest, signal?: AbortSignal) => RemoteStreamHandle<AskFrame, never>
  }
  interface TypertRemoteNamespaceMap {
    'frenchReader': TypertRemoteNamespace$6672656e6368526561646572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
